version : "3"
services:
  decipher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: decipher
    depends_on:
      - decipher-pg
    volumes:
      - .:/var/www/html
    restart: always
    ports:
      - "2233:80"
    environment:
      APP_NAME: 'F+L Laravel Boilerplate'
      APP_DEBUG: 'true'
      APP_URL: 'http://220.223.1.1'
      DB_CONNECTION: 'pgsql'
      QUEUE_CONNECTION: 'database'
      XDEBUG_START_WITH_REQUEST: 'no'
    networks:
      decipher-network:
        ipv4_address: 220.223.1.1
    extra_hosts:
      - host.docker.internal:host-gateway

  decipher-pg:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: test_db
    container_name: decipher-pg
    volumes:
      - decipher-pg-disk:/var/lib/postgres
    networks:
      decipher-network:
        ipv4_address: 220.223.1.2

# On-disk storage of DB data, when containers are stopped/removed
volumes:
  decipher-pg-disk: {}

# Local network for services running using this docker-compose config
networks:
  decipher-network:
    ipam:
      driver: default
      config:
        - subnet: 220.223.0.0/16
